# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77a1b628090932d51bdf661513f75918e6c4eaa051d4a10ad47e2204e8f97824fe32aaa46f37a2f67d048f186a15738e02dafca5a15048dde8bd2a34d00ea6ba

test:
  secret_key_base: 4074713628ac01529708f38e4ee25592c4cae4551c7ef0f0dfcef8cd98cd6063eeac51bb17e544a9fffa42e9bf84f3e69561489d5eed63aead8a80a389d07e94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
